"""Deterministic PageSpec generation for Req2Web."""

from .builder import PageSpecBuilder
from .consistency import (
    CHECK_STATUSES,
    CONSISTENCY_REPORT_SCHEMA_VERSION,
    ConsistencyCheck,
    ConsistencyReport,
    MinimalConsistencyChecker,
)
from .guided_builder import (
    GUIDED_PAGE_SPEC_BUILD_RESULT_SCHEMA_VERSION,
    AffectedPageSpecField,
    GuidanceDecision,
    GuidedPageSpecBuildResult,
    RetrievalGuidedPageSpecBuilder,
)
from .renderer import (
    RENDER_MANIFEST_SCHEMA_VERSION,
    SUPPORTED_COMPONENT_TYPES,
    DeterministicPageRenderer,
    RenderResult,
)
from .result_package import (
    RESULT_PACKAGE_SCHEMA_VERSION,
    RESULT_SUMMARY_SCHEMA_VERSION,
    DeterministicResultPackager,
    ResultPackage,
    ResultPackageError,
)
from .retrieval_guidance import (
    RETRIEVAL_GUIDANCE_SCHEMA_VERSION,
    GuidanceItem,
    GuidanceSource,
    RetrievalGuidance,
    RetrievalGuidanceBuilder,
    UseCaseGuidanceTrace,
)
from .schema import (
    PAGE_SPEC_SCHEMA_VERSION,
    AcceptanceCheck,
    ComponentSpec,
    ConstraintSpec,
    EvidenceReference,
    InteractionSpec,
    LayoutSpec,
    PageSpec,
    PageState,
    PageUseCase,
    SectionSpec,
    TraceabilitySpec,
    UseCaseTrace,
)

__all__ = [
    "PAGE_SPEC_SCHEMA_VERSION",
    "AcceptanceCheck",
    "CHECK_STATUSES",
    "ComponentSpec",
    "CONSISTENCY_REPORT_SCHEMA_VERSION",
    "ConsistencyCheck",
    "ConsistencyReport",
    "ConstraintSpec",
    "DeterministicPageRenderer",
    "EvidenceReference",
    "GUIDED_PAGE_SPEC_BUILD_RESULT_SCHEMA_VERSION",
    "GuidanceDecision",
    "GuidedPageSpecBuildResult",
    "InteractionSpec",
    "LayoutSpec",
    "MinimalConsistencyChecker",
    "PageSpec",
    "PageSpecBuilder",
    "PageState",
    "PageUseCase",
    "AffectedPageSpecField",
    "RENDER_MANIFEST_SCHEMA_VERSION",
    "RESULT_PACKAGE_SCHEMA_VERSION",
    "RESULT_SUMMARY_SCHEMA_VERSION",
    "RenderResult",
    "ResultPackage",
    "ResultPackageError",
    "RETRIEVAL_GUIDANCE_SCHEMA_VERSION",
    "RetrievalGuidance",
    "RetrievalGuidanceBuilder",
    "RetrievalGuidedPageSpecBuilder",
    "SectionSpec",
    "SUPPORTED_COMPONENT_TYPES",
    "GuidanceItem",
    "GuidanceSource",
    "DeterministicResultPackager",
    "TraceabilitySpec",
    "UseCaseTrace",
    "UseCaseGuidanceTrace",
]
