"""Detector-visible structural bundle API.

Injector mutation requests, fragment metadata, injector audits, and evaluator-only
gold remain internal.  Callers may only import the parity-validated bundle
assembler and its structural records from this package namespace.
"""
from .bundle import (
    BLINDED_BUNDLE_PARITY_SCHEMA_VERSION,
    BLINDED_FAULT_BUNDLE_SCHEMA_VERSION,
    BlindedBundleFile,
    BlindedBundleInventoryParityReport,
    BlindedFaultBundleRecord,
    BlindedFaultBundleSource,
    FaultBundleError,
    assemble_blinded_fault_bundle,
    load_blinded_fault_bundle,
    validate_blinded_bundle_inventory_parity,
)

from .repair_policy import (
    DETERMINISTIC_REPAIR_AUTHORIZED,
    FALLBACK_REQUIRED,
    NO_ACTION,
    REPAIR_AUTHORIZATION_SCHEMA_VERSION,
    REPAIR_AUTHORIZATION_STATUSES,
    REPAIR_POLICY_SCHEMA_VERSION,
    RepairAuthorization,
    RepairPolicyError,
    authorize_fault_detection_report,
    write_repair_authorization,
)
from .repair_executor import (
    REPAIR_EXECUTION_REPORT_SCHEMA_VERSION,
    RepairExecutionError,
    RepairExecutionFileDelta,
    RepairExecutionReport,
    execute_authorized_deterministic_repair,
    write_repair_execution_report,
)
from .fallback_delivery import (
    FALLBACK_DELIVERY_REPORT_SCHEMA_VERSION,
    FROZEN_G0_FALLBACK_RECORD_SCHEMA_VERSION,
    FallbackDeliveryError,
    FallbackDeliveryReport,
    FrozenG0FallbackRecord,
    FrozenG0Provenance,
    FrozenPackageFile,
    deliver_frozen_g0_fallback,
    freeze_g0_fallback_package,
)


from .recovery_outcome import (
    DETERMINISTIC_RECOVERY_OUTCOME_MANIFEST_SCHEMA_VERSION,
    DETERMINISTIC_RECOVERY_OUTCOME_SCHEMA_VERSION,
    FALLBACK_DELIVERY,
    FAILED_DELIVERY,
    FIRST_PASS_SUCCESS,
    M2_DEVELOPMENT_FAULT_COPY_SCOPE,
    RECOVERED_SUCCESS,
    RECOVERY_OUTCOME_STATUSES,
    DeterministicRecoveryOutcome,
    DeterministicRecoveryOutcomeError,
    RecoveryOutcomeFile,
    execute_deterministic_development_recovery,
)

from .detector import (
    AMBIGUOUS_MULTIPLE_FAULTS,
    DOM_COMPONENT_STABLE_ID_MISMATCH,
    FAULT_DETECTED,
    FAULT_DETECTION_REPORT_SCHEMA_VERSION,
    FAULT_DETECTION_STATUSES,
    INSPECTOR_TRACE_RELATION_INTEGRITY_MISMATCH,
    IGNORED_EVIDENCE_MISATTRIBUTED_TO_PAGE_SPEC,
    NO_FAULT_DETECTED,
    PACKAGE_MANIFEST_PATH_MISMATCH,
    PACKAGE_MANIFEST_SHA256_MISMATCH,
    PAGE_SPEC_DANGLING_COMPONENT_REFERENCE,
    UNCLASSIFIED_FAILURE,
    FaultDetectionDiagnostic,
    FaultDetectionError,
    FaultDetectionFinding,
    FaultDetectionReport,
    detect_blinded_fault_bundle,
    write_fault_detection_report,
)

__all__ = [
    "AMBIGUOUS_MULTIPLE_FAULTS",
    "DOM_COMPONENT_STABLE_ID_MISMATCH",
    "FAULT_DETECTED",
    "FAULT_DETECTION_REPORT_SCHEMA_VERSION",
    "FAULT_DETECTION_STATUSES",
    "INSPECTOR_TRACE_RELATION_INTEGRITY_MISMATCH",
    "IGNORED_EVIDENCE_MISATTRIBUTED_TO_PAGE_SPEC",
    "NO_FAULT_DETECTED",
    "PACKAGE_MANIFEST_PATH_MISMATCH",
    "PACKAGE_MANIFEST_SHA256_MISMATCH",
    "PAGE_SPEC_DANGLING_COMPONENT_REFERENCE",
    "UNCLASSIFIED_FAILURE",
    "FaultDetectionDiagnostic",
    "FaultDetectionError",
    "FaultDetectionFinding",
    "FaultDetectionReport",
    "BLINDED_BUNDLE_PARITY_SCHEMA_VERSION",
    "BLINDED_FAULT_BUNDLE_SCHEMA_VERSION",
    "BlindedBundleFile",
    "BlindedBundleInventoryParityReport",
    "BlindedFaultBundleRecord",
    "BlindedFaultBundleSource",
    "FaultBundleError",
    "assemble_blinded_fault_bundle",
    "load_blinded_fault_bundle",
    "validate_blinded_bundle_inventory_parity",
    "detect_blinded_fault_bundle",
    "write_fault_detection_report",
    "DETERMINISTIC_REPAIR_AUTHORIZED",
    "FALLBACK_REQUIRED",
    "NO_ACTION",
    "REPAIR_AUTHORIZATION_SCHEMA_VERSION",
    "REPAIR_AUTHORIZATION_STATUSES",
    "REPAIR_POLICY_SCHEMA_VERSION",
    "RepairAuthorization",
    "RepairPolicyError",
    "authorize_fault_detection_report",
    "write_repair_authorization",
    "REPAIR_EXECUTION_REPORT_SCHEMA_VERSION",
    "RepairExecutionError",
    "RepairExecutionFileDelta",
    "RepairExecutionReport",
    "execute_authorized_deterministic_repair",
    "write_repair_execution_report",
    "DETERMINISTIC_RECOVERY_OUTCOME_MANIFEST_SCHEMA_VERSION",
    "DETERMINISTIC_RECOVERY_OUTCOME_SCHEMA_VERSION",
    "FALLBACK_DELIVERY",
    "FAILED_DELIVERY",
    "FIRST_PASS_SUCCESS",
    "M2_DEVELOPMENT_FAULT_COPY_SCOPE",
    "RECOVERED_SUCCESS",
    "RECOVERY_OUTCOME_STATUSES",
    "DeterministicRecoveryOutcome",
    "DeterministicRecoveryOutcomeError",
    "RecoveryOutcomeFile",
    "execute_deterministic_development_recovery",
    "FALLBACK_DELIVERY_REPORT_SCHEMA_VERSION",
    "FROZEN_G0_FALLBACK_RECORD_SCHEMA_VERSION",
    "FallbackDeliveryError",
    "FallbackDeliveryReport",
    "FrozenG0FallbackRecord",
    "FrozenG0Provenance",
    "FrozenPackageFile",
    "deliver_frozen_g0_fallback",
    "freeze_g0_fallback_package",
]
