"""Local-only stateful constrained decoding for one semantic-candidate call.

The controller in this module is deliberately narrower than a general JSON
grammar.  It fixes the versioned semantic-candidate shape, lets the model
declare bounded semantic entities, and constrains later references to the
resulting symbol table.  It never edits generated bytes and it does not create
components, states, interactions, or acceptance checks on the model's behalf.

The public callback is compatible with Transformers'
``prefix_allowed_tokens_fn`` for batch size one, greedy decoding, and one beam.
This is an experimental optional spike module; it is not wired into the default
Provider or trusted-remote executor and is not a production routing path.
"""

from __future__ import annotations

from dataclasses import dataclass
import hashlib
import json
import math
import time
from typing import Iterable, Mapping, Sequence

from req2web_provider.semantic_candidate import (
    MODEL_SEMANTIC_CANDIDATE_SCHEMA_VERSION,
    ProviderRawResponse,
    parse_provider_raw_response,
)


STATEFUL_CONSTRAINED_DECODING_AUDIT_SCHEMA_VERSION = (
    "req2web.runtime.stateful_constrained_decoding.audit.v1"
)
STATEFUL_CONSTRAINED_DECODING_COMPLETION_SCHEMA_VERSION = (
    "req2web.runtime.stateful_constrained_decoding.completion.v1"
)
STATEFUL_CONSTRAINED_GENERATION_TREATMENT_ID = (
    "stateful_constrained_generation_v1"
)
STATEFUL_CONSTRAINED_GENERATION_TREATMENT_VERSION = "1"

_STABLE_ID_FIRST = frozenset("abcdefghijklmnopqrstuvwxyz")
_STABLE_ID_REST = frozenset("abcdefghijklmnopqrstuvwxyz0123456789-")
_JSON_HEX_DIGITS = frozenset("0123456789abcdefABCDEF")
_JSON_SIMPLE_ESCAPES = {
    '"': '"',
    "\\": "\\",
    "/": "/",
    "b": "\b",
    "f": "\f",
    "n": "\n",
    "r": "\r",
    "t": "\t",
}
_SAFE_ERROR_CODES = frozenset(
    {
        "invalid_configuration",
        "unsupported_batch",
        "unsupported_beam",
        "unsupported_sampling",
        "tokenizer_incompatible",
        "prefix_divergence",
        "parser_state_drift",
        "no_legal_token",
        "resource_cap_exceeded",
        "incomplete_generation",
        "invalid_completion",
        "controller_closed",
    }
)
_CONSTRAINT_OWNED_FIELDS = (
    "schema_version",
    "json_shape_and_key_order",
    "stable_id_syntax",
    "duplicate_or_illegal_stable_id_exclusion",
    "undefined_reference_exclusion",
    "non_self_loop_exclusion",
    "approved_use_case_membership",
    "section_component_ownership",
    "use_case_and_acceptance_coverage",
    "coverage_forced_array_continuation",
    "use_case_mappings_derivation",
    "collection_string_token_and_elapsed_caps",
    "sections[*].stable_id_from_layout_declaration",
    "components[*].stable_id_from_section_declaration",
    "components[*].section_stable_id_from_ownership",
    "constraints",
    "use_case_mappings",
    "claimed_attribution_edges",
)
_MODEL_OWNED_FIELDS = (
    "title",
    "layout.pattern",
    "layout.section_stable_ids",
    "sections[*].title",
    "sections[*].purpose",
    "sections[*].component_stable_ids",
    "sections[*].use_case_ids",
    "components[*].component_type",
    "components[*].label",
    "components[*].purpose",
    "states[*].stable_id",
    "states[*].name",
    "states[*].description",
    "states[*].visible_component_stable_ids",
    "interactions[*].stable_id",
    "interactions[*].trigger_component_stable_id",
    "interactions[*].source_state_stable_id",
    "interactions[*].action",
    "interactions[*].target_state_stable_id",
    "interactions[*].user_feedback",
    "interactions[*].use_case_ids",
    "acceptance_checks[*].stable_id",
    "acceptance_checks[*].description",
    "acceptance_checks[*].use_case_ids",
    "acceptance_checks[*].state_stable_id",
)


class StatefulConstrainedDecodingError(RuntimeError):
    """Stable fail-closed error raised by the constrained decoder."""

    def __init__(self, code: str, message: str) -> None:
        if code not in _SAFE_ERROR_CODES:
            raise ValueError("unknown constrained-decoding error code")
        super().__init__(message)
        self.code = code


class _PrefixRejected(ValueError):
    def __init__(self, code: str) -> None:
        super().__init__(code)
        self.code = code


@dataclass(frozen=True)
class ConstraintLimits:
    """Hard complexity limits for one candidate."""

    max_sections: int = 8
    max_components: int = 32
    max_states: int = 16
    max_interactions: int = 24
    max_acceptance_checks: int = 16
    max_stable_id_chars: int = 96
    max_text_chars: int = 512
    max_generated_tokens: int = 8192
    max_token_piece_chars: int = 48
    max_elapsed_seconds: float = 3600.0

    def validate(self) -> None:
        values = (
            self.max_sections,
            self.max_components,
            self.max_states,
            self.max_interactions,
            self.max_acceptance_checks,
            self.max_stable_id_chars,
            self.max_text_chars,
            self.max_generated_tokens,
            self.max_token_piece_chars,
        )
        if any(type(value) is not int or value <= 0 for value in values):
            raise StatefulConstrainedDecodingError(
                "invalid_configuration", "constraint limits must be positive integers"
            )
        if self.max_sections > 32:
            raise StatefulConstrainedDecodingError(
                "invalid_configuration", "section limit exceeds the treatment cap"
            )
        if self.max_components > 128:
            raise StatefulConstrainedDecodingError(
                "invalid_configuration", "component limit exceeds the treatment cap"
            )
        if self.max_states < 2 or self.max_states > 64:
            raise StatefulConstrainedDecodingError(
                "invalid_configuration", "state limit is outside the treatment range"
            )
        if self.max_interactions > 128 or self.max_acceptance_checks > 64:
            raise StatefulConstrainedDecodingError(
                "invalid_configuration", "relation limit exceeds the treatment cap"
            )
        if self.max_stable_id_chars > 96 or self.max_text_chars > 2048:
            raise StatefulConstrainedDecodingError(
                "invalid_configuration", "string limit exceeds the strict contract cap"
            )
        if self.max_generated_tokens > 32768 or self.max_token_piece_chars > 128:
            raise StatefulConstrainedDecodingError(
                "invalid_configuration", "token limit exceeds the treatment cap"
            )
        if (
            isinstance(self.max_elapsed_seconds, bool)
            or not isinstance(self.max_elapsed_seconds, (int, float))
            or not math.isfinite(self.max_elapsed_seconds)
            or self.max_elapsed_seconds <= 0
            or self.max_elapsed_seconds > 86400
        ):
            raise StatefulConstrainedDecodingError(
                "invalid_configuration", "elapsed-time cap is invalid"
            )


@dataclass(frozen=True)
class SymbolTableTransition:
    sequence: int
    event: str
    symbol_kind: str
    stable_id: str
    relation: str

    def to_dict(self) -> dict[str, object]:
        return {
            "sequence": self.sequence,
            "event": self.event,
            "symbol_kind": self.symbol_kind,
            "stable_id": self.stable_id,
            "relation": self.relation,
        }


@dataclass(frozen=True)
class ForcedTokenPosition:
    generated_position: int
    token_id: int
    reason: str

    def to_dict(self) -> dict[str, object]:
        return {
            "generated_position": self.generated_position,
            "token_id": self.token_id,
            "reason": self.reason,
        }


@dataclass(frozen=True)
class StatefulConstraintAuditSummary:
    schema_version: str
    treatment_id: str
    treatment_version: str
    status: str
    execution_profile: str
    success_interpretation: str
    unconstrained_first_pass_model_success_claimed: bool
    formal_quality_claimed: bool
    h1_or_gold_used: bool
    raw_repair_performed: bool
    approved_use_case_ids: tuple[str, ...]
    model_owned_fields: tuple[str, ...]
    constraint_owned_fields: tuple[str, ...]
    forced_token_positions: tuple[ForcedTokenPosition, ...]
    symbol_table_transitions: tuple[SymbolTableTransition, ...]
    callback_count: int
    mask_compute_count: int
    model_vocabulary_size: int
    allowed_token_observations: int
    masked_token_observations: int
    elapsed_milliseconds: int
    rejection_counts: tuple[tuple[str, int], ...]
    generated_token_ids: tuple[int, ...]
    raw_token_ids: tuple[int, ...]
    generation_eos_token_id: int
    complete: bool
    raw_unmodified: bool
    raw_byte_length: int
    raw_sha256: str
    error_code: str

    def to_dict(self) -> dict[str, object]:
        return {
            "schema_version": self.schema_version,
            "treatment_id": self.treatment_id,
            "treatment_version": self.treatment_version,
            "status": self.status,
            "execution_profile": self.execution_profile,
            "success_interpretation": self.success_interpretation,
            "unconstrained_first_pass_model_success_claimed": (
                self.unconstrained_first_pass_model_success_claimed
            ),
            "formal_quality_claimed": self.formal_quality_claimed,
            "h1_or_gold_used": self.h1_or_gold_used,
            "raw_repair_performed": self.raw_repair_performed,
            "approved_use_case_ids": list(self.approved_use_case_ids),
            "model_owned_fields": list(self.model_owned_fields),
            "constraint_owned_fields": list(self.constraint_owned_fields),
            "forced_token_positions": [
                item.to_dict() for item in self.forced_token_positions
            ],
            "symbol_table_transitions": [
                item.to_dict() for item in self.symbol_table_transitions
            ],
            "callback_count": self.callback_count,
            "mask_compute_count": self.mask_compute_count,
            "model_vocabulary_size": self.model_vocabulary_size,
            "allowed_token_observations": self.allowed_token_observations,
            "masked_token_observations": self.masked_token_observations,
            "elapsed_milliseconds": self.elapsed_milliseconds,
            "rejection_counts": {
                key: value for key, value in self.rejection_counts
            },
            "generated_token_ids": list(self.generated_token_ids),
            "raw_token_ids": list(self.raw_token_ids),
            "generation_eos_token_id": self.generation_eos_token_id,
            "complete": self.complete,
            "raw_unmodified": self.raw_unmodified,
            "raw_byte_length": self.raw_byte_length,
            "raw_sha256": self.raw_sha256,
            "error_code": self.error_code,
        }


@dataclass(frozen=True)
class StatefulConstrainedGenerationCompletion:
    schema_version: str
    treatment_id: str
    treatment_version: str
    raw_bytes: bytes
    raw_token_ids: tuple[int, ...]
    generated_token_ids: tuple[int, ...]
    raw_sha256: str
    candidate_sha256: str
    complete: bool
    raw_unmodified: bool
    audit: StatefulConstraintAuditSummary

    def to_dict(self) -> dict[str, object]:
        return {
            "schema_version": self.schema_version,
            "treatment_id": self.treatment_id,
            "treatment_version": self.treatment_version,
            "raw_byte_length": len(self.raw_bytes),
            "raw_sha256": self.raw_sha256,
            "raw_token_ids": list(self.raw_token_ids),
            "generated_token_ids": list(self.generated_token_ids),
            "candidate_sha256": self.candidate_sha256,
            "complete": self.complete,
            "raw_unmodified": self.raw_unmodified,
            "audit": self.audit.to_dict(),
        }


@dataclass
class _Task:
    kind: str
    tag: str = ""
    literal: str = ""
    options: tuple[str, ...] = ()
    values: tuple[str, ...] = ()
    position: int = 0
    value: str = ""
    decoded_value: str = ""
    opened: bool = False
    escape_state: str = ""
    unicode_digits: str = ""
    min_length: int = 1
    max_length: int = 1
    mask_code: str = "json_shape"


def _json_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=True, separators=(",", ":"))


def _literal(value: str, *, mask_code: str = "constraint_owned_literal") -> _Task:
    if not value:
        raise ValueError("literal task must not be empty")
    return _Task(kind="literal", literal=value, mask_code=mask_code)


def _text(
    tag: str,
    *,
    min_length: int,
    max_length: int,
    mask_code: str = "json_text_shape",
) -> _Task:
    return _Task(
        kind="text",
        tag=tag,
        min_length=min_length,
        max_length=max_length,
        mask_code=mask_code,
    )


def _stable_id(tag: str, *, max_length: int) -> _Task:
    return _Task(
        kind="stable_id",
        tag=tag,
        min_length=1,
        max_length=max_length,
        mask_code="stable_id_shape_or_duplicate",
    )


def _choice(
    tag: str,
    values: Iterable[str],
    *,
    mask_code: str,
    encoded: bool = False,
) -> _Task:
    raw_values = tuple(values)
    options = raw_values if encoded else tuple(_json_string(item) for item in raw_values)
    if not options:
        return _Task(
            kind="choice",
            tag=tag,
            options=(),
            values=(),
            mask_code=mask_code,
        )
    return _Task(
        kind="choice",
        tag=tag,
        options=options,
        values=raw_values,
        mask_code=mask_code,
    )


def _boundary(tag: str, values: Iterable[str], *, mask_code: str) -> _Task:
    choices = tuple(values)
    return _Task(
        kind="boundary",
        tag=tag,
        options=choices,
        values=choices,
        mask_code=mask_code,
    )


class _SemanticCandidateMachine:
    def __init__(
        self,
        approved_use_case_ids: tuple[str, ...],
        limits: ConstraintLimits,
    ) -> None:
        self.approved_use_case_ids = approved_use_case_ids
        self.limits = limits
        self.tasks: list[_Task] = [
            _literal(
                '{"schema_version":'
                + _json_string(MODEL_SEMANTIC_CANDIDATE_SCHEMA_VERSION)
                + ',"title":'
            ),
            _text("title", min_length=1, max_length=limits.max_text_chars),
        ]
        self.global_ids: set[str] = set()
        self.layout_section_ids: list[str] = []
        self.sections: list[dict[str, object]] = []
        self.component_owners: list[tuple[str, str]] = []
        self.states: list[str] = []
        self.interactions: list[dict[str, object]] = []
        self.acceptance_checks: list[dict[str, object]] = []
        self.current_section_index = -1
        self.current_section_components: list[str] = []
        self.current_section_use_cases: list[str] = []
        self.current_state_id = ""
        self.current_state_components: list[str] = []
        self.current_interaction: dict[str, object] = {}
        self.current_check: dict[str, object] = {}
        self.transitions: list[SymbolTableTransition] = []

    @property
    def complete(self) -> bool:
        return not self.tasks

    @property
    def current_task(self) -> _Task | None:
        return self.tasks[0] if self.tasks else None

    def _push(self, *tasks: _Task) -> None:
        self.tasks.extend(tasks)

    def _transition(
        self,
        event: str,
        symbol_kind: str,
        stable_id: str,
        relation: str,
    ) -> None:
        self.transitions.append(
            SymbolTableTransition(
                sequence=len(self.transitions) + 1,
                event=event,
                symbol_kind=symbol_kind,
                stable_id=stable_id,
                relation=relation,
            )
        )

    def _declare(self, kind: str, value: str, relation: str) -> None:
        if value in self.global_ids:
            raise _PrefixRejected("duplicate_stable_id")
        self.global_ids.add(value)
        self._transition("declared", kind, value, relation)

    def can_close_string(self, task: _Task) -> bool:
        if not task.opened:
            return False
        if task.kind == "text":
            return (
                not task.escape_state
                and len(task.decoded_value) >= task.min_length
                and task.decoded_value == task.decoded_value.strip()
            )
        if task.kind == "stable_id":
            return (
                len(task.value) >= task.min_length
                and task.value not in self.global_ids
            )
        return False

    @staticmethod
    def _append_decoded_text(task: _Task, character: str) -> None:
        if len(task.decoded_value) >= task.max_length:
            raise _PrefixRejected("string_length_cap")
        if not task.decoded_value and character.isspace():
            raise _PrefixRejected("text_leading_space")
        task.decoded_value += character

    def feed(self, piece: str) -> None:
        if not isinstance(piece, str) or not piece:
            raise _PrefixRejected("tokenizer_piece_invalid")
        for character in piece:
            if not self.tasks:
                raise _PrefixRejected("trailing_content")
            task = self.tasks[0]
            completed, value = self._consume(task, character)
            if completed:
                self.tasks.pop(0)
                self._on_complete(task, value)

    def _consume(self, task: _Task, character: str) -> tuple[bool, str]:
        if task.kind == "literal":
            if task.position >= len(task.literal) or task.literal[task.position] != character:
                raise _PrefixRejected("literal_mismatch")
            task.position += 1
            return task.position == len(task.literal), task.literal

        if task.kind in {"choice", "boundary"}:
            candidate = task.value + character
            viable = [option for option in task.options if option.startswith(candidate)]
            if not viable:
                raise _PrefixRejected(task.mask_code)
            task.value = candidate
            if candidate in task.options:
                index = task.options.index(candidate)
                if any(
                    option != candidate and option.startswith(candidate)
                    for option in task.options
                ):
                    return False, ""
                return True, task.values[index]
            return False, ""

        if task.kind not in {"text", "stable_id"}:
            raise _PrefixRejected("parser_state_invalid")
        if not task.opened:
            if character != '"':
                raise _PrefixRejected(task.mask_code)
            task.opened = True
            return False, ""
        if task.kind == "text":
            if task.escape_state == "escape":
                if len(task.value) >= task.max_length * 6:
                    raise _PrefixRejected("string_length_cap")
                task.value += character
                if character == "u":
                    task.escape_state = "unicode"
                    task.unicode_digits = ""
                    return False, ""
                decoded = _JSON_SIMPLE_ESCAPES.get(character)
                if decoded is None:
                    raise _PrefixRejected("json_escape_invalid")
                self._append_decoded_text(task, decoded)
                task.escape_state = ""
                return False, ""
            if task.escape_state == "unicode":
                if character not in _JSON_HEX_DIGITS:
                    raise _PrefixRejected("json_unicode_escape_invalid")
                if len(task.value) >= task.max_length * 6:
                    raise _PrefixRejected("string_length_cap")
                task.value += character
                task.unicode_digits += character
                if len(task.unicode_digits) == 4:
                    self._append_decoded_text(
                        task, chr(int(task.unicode_digits, 16))
                    )
                    task.escape_state = ""
                    task.unicode_digits = ""
                return False, ""
            if character == '"':
                if not self.can_close_string(task):
                    raise _PrefixRejected("string_closure_invalid")
                return True, task.decoded_value
            if character == "\\":
                if (
                    len(task.decoded_value) >= task.max_length
                    or len(task.value) >= task.max_length * 6
                ):
                    raise _PrefixRejected("string_length_cap")
                task.value += character
                task.escape_state = "escape"
                return False, ""
            if ord(character) < 0x20:
                raise _PrefixRejected("json_control_character_invalid")
            if len(task.value) >= task.max_length * 6:
                raise _PrefixRejected("string_length_cap")
            self._append_decoded_text(task, character)
            task.value += character
            return False, ""

        if character == '"':
            if not self.can_close_string(task):
                if task.value in self.global_ids:
                    raise _PrefixRejected("duplicate_stable_id")
                raise _PrefixRejected("string_closure_invalid")
            return True, task.value
        if len(task.value) >= task.max_length:
            raise _PrefixRejected("string_length_cap")
        allowed = _STABLE_ID_FIRST if not task.value else _STABLE_ID_REST
        if character not in allowed:
            raise _PrefixRejected("stable_id_character_invalid")
        task.value += character
        return False, ""

    def _on_complete(self, task: _Task, value: str) -> None:
        handler = getattr(self, f"_complete_{task.tag}", None)
        if handler is not None:
            handler(value)

    def _complete_title(self, _: str) -> None:
        self._push(
            _literal(',"layout":{"pattern":'),
            _text(
                "layout_pattern",
                min_length=1,
                max_length=self.limits.max_text_chars,
            ),
        )

    def _complete_layout_pattern(self, _: str) -> None:
        self._push(
            _literal(',"section_stable_ids":['),
            _stable_id(
                "layout_section_id",
                max_length=self.limits.max_stable_id_chars,
            ),
        )

    def _complete_layout_section_id(self, value: str) -> None:
        self._declare("section", value, "layout.section_stable_ids")
        self.layout_section_ids.append(value)
        choices: list[str] = []
        if len(self.layout_section_ids) < self.limits.max_sections:
            choices.append(",")
        choices.append("]")
        self._push(
            _boundary(
                "layout_sections_boundary",
                choices,
                mask_code="section_count_cap",
            )
        )

    def _complete_layout_sections_boundary(self, value: str) -> None:
        if value == ",":
            self._push(
                _stable_id(
                    "layout_section_id",
                    max_length=self.limits.max_stable_id_chars,
                )
            )
            return
        self.current_section_index = 0
        self._push(_literal('},"sections":['))
        self._start_section()

    def _start_section(self) -> None:
        section_id = self.layout_section_ids[self.current_section_index]
        self.current_section_components = []
        self.current_section_use_cases = []
        self._transition(
            "definition_bound",
            "section",
            section_id,
            "sections[*].stable_id",
        )
        self._push(
            _literal('{"stable_id":' + _json_string(section_id) + ',"title":'),
            _text(
                "section_title",
                min_length=1,
                max_length=self.limits.max_text_chars,
            ),
        )

    def _complete_section_title(self, _: str) -> None:
        self._push(
            _literal(',"purpose":'),
            _text(
                "section_purpose",
                min_length=1,
                max_length=self.limits.max_text_chars,
            ),
        )

    def _complete_section_purpose(self, _: str) -> None:
        if len(self.component_owners) >= self.limits.max_components:
            raise _PrefixRejected("component_count_cap")
        self._push(
            _literal(',"component_stable_ids":['),
            _stable_id(
                "section_component_id",
                max_length=self.limits.max_stable_id_chars,
            ),
        )

    def _complete_section_component_id(self, value: str) -> None:
        owner = self.layout_section_ids[self.current_section_index]
        self._declare("component", value, f"owned_by:{owner}")
        self.current_section_components.append(value)
        self.component_owners.append((value, owner))
        choices: list[str] = []
        if len(self.component_owners) < self.limits.max_components:
            choices.append(",")
        choices.append("]")
        self._push(
            _boundary(
                "section_components_boundary",
                choices,
                mask_code="component_count_cap",
            )
        )

    def _complete_section_components_boundary(self, value: str) -> None:
        if value == ",":
            self._push(
                _stable_id(
                    "section_component_id",
                    max_length=self.limits.max_stable_id_chars,
                )
            )
            return
        self._push(
            _literal(',"use_case_ids":['),
            _choice(
                "section_use_case",
                self.approved_use_case_ids,
                mask_code="unapproved_use_case",
            ),
        )

    def _complete_section_use_case(self, value: str) -> None:
        self.current_section_use_cases.append(value)
        remaining = [
            item
            for item in self.approved_use_case_ids
            if item not in self.current_section_use_cases
        ]
        choices: list[str] = []
        if remaining:
            choices.append(",")
        is_last = self.current_section_index == len(self.layout_section_ids) - 1
        covered = {
            use_case_id
            for section in self.sections
            for use_case_id in section["use_case_ids"]  # type: ignore[index]
        } | set(self.current_section_use_cases)
        if not is_last or covered == set(self.approved_use_case_ids):
            choices.append("]")
        self._push(
            _boundary(
                "section_use_cases_boundary",
                choices,
                mask_code="section_use_case_coverage_incomplete",
            )
        )

    def _complete_section_use_cases_boundary(self, value: str) -> None:
        if value == ",":
            remaining = [
                item
                for item in self.approved_use_case_ids
                if item not in self.current_section_use_cases
            ]
            self._push(
                _choice(
                    "section_use_case",
                    remaining,
                    mask_code="unapproved_or_duplicate_use_case",
                )
            )
            return
        section_id = self.layout_section_ids[self.current_section_index]
        self.sections.append(
            {
                "stable_id": section_id,
                "component_stable_ids": tuple(self.current_section_components),
                "use_case_ids": tuple(self.current_section_use_cases),
            }
        )
        self._push(_literal("}"))
        self.current_section_index += 1
        if self.current_section_index < len(self.layout_section_ids):
            self._push(_literal(","))
            self._start_section()
            return
        self._push(_literal('],"components":['))
        self._start_component(0)

    def _start_component(self, index: int) -> None:
        component_id, section_id = self.component_owners[index]
        self._transition(
            "definition_bound",
            "component",
            component_id,
            f"components[*].section_stable_id:{section_id}",
        )
        self._push(
            _literal(
                '{"stable_id":'
                + _json_string(component_id)
                + ',"section_stable_id":'
                + _json_string(section_id)
                + ',"component_type":'
            ),
            _text(
                "component_type",
                min_length=1,
                max_length=self.limits.max_text_chars,
            ),
        )

    def _complete_component_type(self, _: str) -> None:
        self._push(
            _literal(',"label":'),
            _text(
                "component_label",
                min_length=1,
                max_length=self.limits.max_text_chars,
            ),
        )

    def _complete_component_label(self, _: str) -> None:
        self._push(
            _literal(',"purpose":'),
            _text(
                "component_purpose",
                min_length=1,
                max_length=self.limits.max_text_chars,
            ),
        )

    def _complete_component_purpose(self, _: str) -> None:
        defined = sum(
            1
            for item in self.transitions
            if item.event == "definition_bound" and item.symbol_kind == "component"
        )
        self._push(_literal("}"))
        if defined < len(self.component_owners):
            self._push(_literal(","))
            self._start_component(defined)
            return
        self._push(_literal('],"states":['))
        self._start_state()

    def _start_state(self) -> None:
        self.current_state_id = ""
        self.current_state_components = []
        self._push(
            _literal('{"stable_id":'),
            _stable_id("state_id", max_length=self.limits.max_stable_id_chars),
        )

    def _complete_state_id(self, value: str) -> None:
        self._declare("state", value, "states[*].stable_id")
        self.current_state_id = value
        self.states.append(value)
        self._push(
            _literal(',"name":'),
            _text(
                "state_name",
                min_length=1,
                max_length=self.limits.max_text_chars,
            ),
        )

    def _complete_state_name(self, _: str) -> None:
        self._push(
            _literal(',"description":'),
            _text(
                "state_description",
                min_length=1,
                max_length=self.limits.max_text_chars,
            ),
        )

    def _complete_state_description(self, _: str) -> None:
        self._push(
            _literal(',"visible_component_stable_ids":['),
            _choice(
                "state_component_or_close",
                ("]", *(_json_string(item[0]) for item in self.component_owners)),
                mask_code="undefined_component_reference",
                encoded=True,
            ),
        )

    def _complete_state_component_or_close(self, value: str) -> None:
        if value == "]":
            self._finish_state()
            return
        decoded = json.loads(value)
        self.current_state_components.append(decoded)
        self._transition(
            "reference_selected",
            "component",
            decoded,
            f"visible_in:{self.current_state_id}",
        )
        self._schedule_state_component_boundary()

    def _schedule_state_component_boundary(self) -> None:
        choices = ["]"]
        if len(self.current_state_components) < len(self.component_owners):
            choices.insert(0, ",")
        self._push(
            _boundary(
                "state_components_boundary",
                choices,
                mask_code="duplicate_component_reference",
            )
        )

    def _complete_state_components_boundary(self, value: str) -> None:
        if value == ",":
            remaining = [
                component_id
                for component_id, _ in self.component_owners
                if component_id not in self.current_state_components
            ]
            self._push(
                _choice(
                    "state_component",
                    remaining,
                    mask_code="undefined_or_duplicate_component_reference",
                )
            )
            return
        self._finish_state()

    def _complete_state_component(self, value: str) -> None:
        self.current_state_components.append(value)
        self._transition(
            "reference_selected",
            "component",
            value,
            f"visible_in:{self.current_state_id}",
        )
        self._schedule_state_component_boundary()

    def _finish_state(self) -> None:
        self._push(_literal("}"))
        choices: list[str] = []
        if len(self.states) < self.limits.max_states:
            choices.append(",")
        if len(self.states) >= 2:
            choices.append("]")
        self._push(
            _boundary(
                "states_boundary",
                choices,
                mask_code="state_count_or_nonselfloop_requirement",
            )
        )

    def _complete_states_boundary(self, value: str) -> None:
        if value == ",":
            self._start_state()
            return
        self._push(_literal(',"interactions":['))
        self._start_interaction()

    def _start_interaction(self) -> None:
        self.current_interaction = {"use_case_ids": []}
        self._push(
            _literal('{"stable_id":'),
            _stable_id(
                "interaction_id",
                max_length=self.limits.max_stable_id_chars,
            ),
        )

    def _complete_interaction_id(self, value: str) -> None:
        self._declare("interaction", value, "interactions[*].stable_id")
        self.current_interaction["stable_id"] = value
        self._push(
            _literal(',"trigger_component_stable_id":'),
            _choice(
                "interaction_trigger",
                (item[0] for item in self.component_owners),
                mask_code="undefined_component_reference",
            ),
        )

    def _complete_interaction_trigger(self, value: str) -> None:
        self.current_interaction["trigger_component_stable_id"] = value
        self._push(
            _literal(',"source_state_stable_id":'),
            _choice(
                "interaction_source",
                self.states,
                mask_code="undefined_state_reference",
            ),
        )

    def _complete_interaction_source(self, value: str) -> None:
        self.current_interaction["source_state_stable_id"] = value
        self._push(
            _literal(',"action":'),
            _text(
                "interaction_action",
                min_length=1,
                max_length=self.limits.max_text_chars,
            ),
        )

    def _complete_interaction_action(self, _: str) -> None:
        source = self.current_interaction["source_state_stable_id"]
        targets = [item for item in self.states if item != source]
        self._push(
            _literal(',"target_state_stable_id":'),
            _choice(
                "interaction_target",
                targets,
                mask_code="undefined_or_self_loop_target",
            ),
        )

    def _complete_interaction_target(self, value: str) -> None:
        if value == self.current_interaction["source_state_stable_id"]:
            raise _PrefixRejected("self_loop_target")
        self.current_interaction["target_state_stable_id"] = value
        self._push(
            _literal(',"user_feedback":'),
            _text(
                "interaction_feedback",
                min_length=1,
                max_length=self.limits.max_text_chars,
            ),
        )

    def _complete_interaction_feedback(self, _: str) -> None:
        self._push(
            _literal(',"use_case_ids":['),
            _choice(
                "interaction_use_case",
                self.approved_use_case_ids,
                mask_code="unapproved_use_case",
            ),
        )

    def _complete_interaction_use_case(self, value: str) -> None:
        use_case_ids = self.current_interaction["use_case_ids"]
        assert isinstance(use_case_ids, list)
        use_case_ids.append(value)
        remaining = [
            item for item in self.approved_use_case_ids if item not in use_case_ids
        ]
        choices = ["]"]
        if remaining:
            choices.insert(0, ",")
        self._push(
            _boundary(
                "interaction_use_cases_boundary",
                choices,
                mask_code="duplicate_interaction_use_case",
            )
        )

    def _complete_interaction_use_cases_boundary(self, value: str) -> None:
        if value == ",":
            use_case_ids = self.current_interaction["use_case_ids"]
            assert isinstance(use_case_ids, list)
            remaining = [
                item
                for item in self.approved_use_case_ids
                if item not in use_case_ids
            ]
            self._push(
                _choice(
                    "interaction_use_case",
                    remaining,
                    mask_code="unapproved_or_duplicate_use_case",
                )
            )
            return
        self.interactions.append(
            {
                **self.current_interaction,
                "use_case_ids": tuple(self.current_interaction["use_case_ids"]),
            }
        )
        self._push(_literal("}"))
        covered = {
            use_case_id
            for interaction in self.interactions
            for use_case_id in interaction["use_case_ids"]  # type: ignore[index]
        }
        choices: list[str] = []
        if len(self.interactions) < self.limits.max_interactions:
            choices.append(",")
        if covered == set(self.approved_use_case_ids):
            choices.append("]")
        self._push(
            _boundary(
                "interactions_boundary",
                choices,
                mask_code="interaction_use_case_coverage_incomplete",
            )
        )

    def _complete_interactions_boundary(self, value: str) -> None:
        if value == ",":
            self._start_interaction()
            return
        self._push(_literal(',"constraints":[],"acceptance_checks":['))
        self._start_check()

    def _start_check(self) -> None:
        self.current_check = {"use_case_ids": []}
        self._push(
            _literal('{"stable_id":'),
            _stable_id(
                "check_id",
                max_length=self.limits.max_stable_id_chars,
            ),
        )

    def _complete_check_id(self, value: str) -> None:
        self._declare("acceptance_check", value, "acceptance_checks[*].stable_id")
        self.current_check["stable_id"] = value
        self._push(
            _literal(',"description":'),
            _text(
                "check_description",
                min_length=8,
                max_length=self.limits.max_text_chars,
            ),
        )

    def _complete_check_description(self, _: str) -> None:
        self._push(
            _literal(',"use_case_ids":['),
            _choice(
                "check_use_case",
                self.approved_use_case_ids,
                mask_code="unapproved_use_case",
            ),
        )

    def _complete_check_use_case(self, value: str) -> None:
        use_case_ids = self.current_check["use_case_ids"]
        assert isinstance(use_case_ids, list)
        use_case_ids.append(value)
        remaining = [
            item for item in self.approved_use_case_ids if item not in use_case_ids
        ]
        choices = ["]"]
        if remaining:
            choices.insert(0, ",")
        self._push(
            _boundary(
                "check_use_cases_boundary",
                choices,
                mask_code="duplicate_check_use_case",
            )
        )

    def _complete_check_use_cases_boundary(self, value: str) -> None:
        if value == ",":
            use_case_ids = self.current_check["use_case_ids"]
            assert isinstance(use_case_ids, list)
            remaining = [
                item
                for item in self.approved_use_case_ids
                if item not in use_case_ids
            ]
            self._push(
                _choice(
                    "check_use_case",
                    remaining,
                    mask_code="unapproved_or_duplicate_use_case",
                )
            )
            return
        self._push(
            _literal(',"state_stable_id":'),
            _choice(
                "check_state",
                self.states,
                mask_code="undefined_state_reference",
            ),
        )

    def _complete_check_state(self, value: str) -> None:
        self.current_check["state_stable_id"] = value
        self.current_check["use_case_ids"] = tuple(
            self.current_check["use_case_ids"]
        )
        self.acceptance_checks.append(dict(self.current_check))
        self._push(_literal("}"))
        covered = {
            use_case_id
            for check in self.acceptance_checks
            for use_case_id in check["use_case_ids"]  # type: ignore[index]
        }
        choices: list[str] = []
        if len(self.acceptance_checks) < self.limits.max_acceptance_checks:
            choices.append(",")
        if covered == set(self.approved_use_case_ids):
            choices.append("]")
        self._push(
            _boundary(
                "checks_boundary",
                choices,
                mask_code="acceptance_use_case_coverage_incomplete",
            )
        )

    def _complete_checks_boundary(self, value: str) -> None:
        if value == ",":
            self._start_check()
            return
        mappings: list[dict[str, object]] = []
        for use_case_id in self.approved_use_case_ids:
            section_ids = [
                str(section["stable_id"])
                for section in self.sections
                if use_case_id in section["use_case_ids"]  # type: ignore[operator]
            ]
            component_ids = [
                component_id
                for component_id, section_id in self.component_owners
                if section_id in section_ids
            ]
            interaction_ids = [
                str(interaction["stable_id"])
                for interaction in self.interactions
                if use_case_id in interaction["use_case_ids"]  # type: ignore[operator]
            ]
            if not section_ids or not component_ids or not interaction_ids:
                raise _PrefixRejected("mapping_source_incomplete")
            mappings.append(
                {
                    "use_case_id": use_case_id,
                    "section_stable_ids": section_ids,
                    "component_stable_ids": component_ids,
                    "interaction_stable_ids": interaction_ids,
                }
            )
            self._transition(
                "mapping_derived",
                "use_case",
                use_case_id,
                "exact_generated_relations",
            )
        mapping_text = json.dumps(
            mappings, ensure_ascii=True, separators=(",", ":")
        )
        self._push(
            _literal(
                ',"use_case_mappings":'
                + mapping_text
                + ',"claimed_attribution_edges":[]}'
            )
        )


class _TokenizerVocabulary:
    def __init__(
        self,
        tokenizer: object,
        limits: ConstraintLimits,
        generation_eos_token_id: int,
        model_vocabulary_size: int,
    ) -> None:
        self.tokenizer = tokenizer
        self.generation_eos_token_id = generation_eos_token_id
        self.model_vocabulary_size = model_vocabulary_size
        token_ids = [
            item
            for item in self._token_ids(tokenizer)
            if item < model_vocabulary_size
        ]
        self.token_ids = tuple(token_ids)
        special_ids = {
            int(item)
            for item in getattr(tokenizer, "all_special_ids", ())
            if type(item) is int and 0 <= item < model_vocabulary_size
        }
        self.id_to_piece: dict[int, str] = {}
        self.exact_piece_ids: dict[str, list[int]] = {}
        self.text_piece_ids_by_length: dict[int, list[int]] = {}
        self.text_initial_piece_ids_by_length: dict[int, list[int]] = {}
        self.stable_initial_piece_ids_by_length: dict[int, list[int]] = {}
        self.stable_continue_piece_ids_by_length: dict[int, list[int]] = {}
        decodable_ids = [
            item
            for item in self.token_ids
            if item != generation_eos_token_id and item not in special_ids
        ]
        for token_id, piece in zip(
            decodable_ids, self._batch_decode(tokenizer, decodable_ids)
        ):
            if not isinstance(piece, str) or not piece:
                continue
            self.id_to_piece[token_id] = piece
            self.exact_piece_ids.setdefault(piece, []).append(token_id)
            length = len(piece)
            if length > limits.max_token_piece_chars:
                continue
            if all(
                ord(character) >= 0x20 and character not in {'"', "\\"}
                for character in piece
            ):
                self.text_piece_ids_by_length.setdefault(length, []).append(token_id)
                if not piece[0].isspace():
                    self.text_initial_piece_ids_by_length.setdefault(
                        length, []
                    ).append(token_id)
            if piece[0] in _STABLE_ID_FIRST and all(
                character in _STABLE_ID_REST for character in piece[1:]
            ):
                self.stable_initial_piece_ids_by_length.setdefault(
                    length, []
                ).append(token_id)
            if all(character in _STABLE_ID_REST for character in piece):
                self.stable_continue_piece_ids_by_length.setdefault(
                    length, []
                ).append(token_id)
        self._max_piece_length = limits.max_token_piece_chars
        self._cache: dict[tuple[str, int], tuple[int, ...]] = {}

    @staticmethod
    def _token_ids(tokenizer: object) -> list[int]:
        getter = getattr(tokenizer, "get_vocab", None)
        if callable(getter):
            vocabulary = getter()
            if not isinstance(vocabulary, Mapping):
                raise StatefulConstrainedDecodingError(
                    "tokenizer_incompatible", "tokenizer vocabulary is invalid"
                )
            ids = sorted(
                {
                    int(value)
                    for value in vocabulary.values()
                    if type(value) is int and value >= 0
                }
            )
            if ids:
                return ids
        try:
            length = len(tokenizer)  # type: ignore[arg-type]
        except (TypeError, AttributeError) as exc:
            raise StatefulConstrainedDecodingError(
                "tokenizer_incompatible", "tokenizer has no enumerable vocabulary"
            ) from exc
        if type(length) is not int or length <= 0:
            raise StatefulConstrainedDecodingError(
                "tokenizer_incompatible", "tokenizer vocabulary is empty"
            )
        return list(range(length))

    @staticmethod
    def _batch_decode(tokenizer: object, token_ids: Sequence[int]) -> list[str]:
        decoder = getattr(tokenizer, "batch_decode", None)
        if callable(decoder):
            result: list[str] = []
            for start in range(0, len(token_ids), 4096):
                batch = [[item] for item in token_ids[start : start + 4096]]
                try:
                    values = decoder(
                        batch,
                        skip_special_tokens=False,
                        clean_up_tokenization_spaces=False,
                    )
                except TypeError:
                    values = decoder(batch, skip_special_tokens=False)
                if not isinstance(values, list) or len(values) != len(batch):
                    raise StatefulConstrainedDecodingError(
                        "tokenizer_incompatible",
                        "tokenizer batch decoding is inconsistent",
                    )
                result.extend(str(item) for item in values)
            return result
        single = getattr(tokenizer, "decode", None)
        if not callable(single):
            raise StatefulConstrainedDecodingError(
                "tokenizer_incompatible", "tokenizer has no decode interface"
            )
        result = []
        for token_id in token_ids:
            try:
                piece = single(
                    [token_id],
                    skip_special_tokens=False,
                    clean_up_tokenization_spaces=False,
                )
            except TypeError:
                piece = single([token_id], skip_special_tokens=False)
            result.append(str(piece))
        return result

    def decode_ids(self, token_ids: Sequence[int]) -> str:
        decoder = getattr(self.tokenizer, "decode", None)
        if not callable(decoder):
            raise StatefulConstrainedDecodingError(
                "tokenizer_incompatible", "tokenizer has no decode interface"
            )
        try:
            value = decoder(
                list(token_ids),
                skip_special_tokens=False,
                clean_up_tokenization_spaces=False,
            )
        except TypeError:
            value = decoder(list(token_ids), skip_special_tokens=False)
        if not isinstance(value, str):
            raise StatefulConstrainedDecodingError(
                "tokenizer_incompatible", "tokenizer decode result is not text"
            )
        return value

    def exact(self, value: str) -> tuple[int, ...]:
        return tuple(self.exact_piece_ids.get(value, ()))

    def prefix_tokens(self, suffix: str) -> tuple[int, ...]:
        result: list[int] = []
        upper = min(len(suffix), self._max_piece_length)
        for length in range(1, upper + 1):
            result.extend(self.exact_piece_ids.get(suffix[:length], ()))
        return tuple(result)

    def _bounded(
        self,
        key: str,
        groups: Mapping[int, list[int]],
        remaining: int,
    ) -> tuple[int, ...]:
        bounded = min(remaining, self._max_piece_length)
        cache_key = (key, bounded)
        cached = self._cache.get(cache_key)
        if cached is not None:
            return cached
        result: list[int] = []
        for length in range(1, bounded + 1):
            result.extend(groups.get(length, ()))
        value = tuple(result)
        self._cache[cache_key] = value
        return value

    def text_tokens(self, remaining: int, *, initial: bool) -> tuple[int, ...]:
        groups = (
            self.text_initial_piece_ids_by_length
            if initial
            else self.text_piece_ids_by_length
        )
        return self._bounded("text_initial" if initial else "text", groups, remaining)

    def stable_tokens(self, remaining: int, *, initial: bool) -> tuple[int, ...]:
        groups = (
            self.stable_initial_piece_ids_by_length
            if initial
            else self.stable_continue_piece_ids_by_length
        )
        return self._bounded(
            "stable_initial" if initial else "stable", groups, remaining
        )


class StatefulConstrainedGeneration:
    """One-call stateful constraint controller for a semantic candidate."""

    def __init__(
        self,
        tokenizer: object,
        prompt_token_length: int,
        approved_use_case_ids: Sequence[str],
        *,
        generation_eos_token_id: int,
        model_vocabulary_size: int,
        limits: ConstraintLimits | None = None,
        batch_size: int = 1,
        num_beams: int = 1,
        do_sample: bool = False,
        num_return_sequences: int = 1,
    ) -> None:
        self.limits = limits or ConstraintLimits()
        self.limits.validate()
        if type(prompt_token_length) is not int or prompt_token_length <= 0:
            raise StatefulConstrainedDecodingError(
                "invalid_configuration", "prompt token length must be positive"
            )
        if type(model_vocabulary_size) is not int or model_vocabulary_size <= 0:
            raise StatefulConstrainedDecodingError(
                "invalid_configuration", "model vocabulary size must be positive"
            )
        if (
            type(generation_eos_token_id) is not int
            or generation_eos_token_id < 0
            or generation_eos_token_id >= model_vocabulary_size
        ):
            raise StatefulConstrainedDecodingError(
                "invalid_configuration",
                "generation EOS token must be inside the model vocabulary",
            )
        if type(batch_size) is not int or batch_size != 1:
            raise StatefulConstrainedDecodingError(
                "unsupported_batch", "stateful decoding supports batch size one"
            )
        if type(num_beams) is not int or num_beams != 1:
            raise StatefulConstrainedDecodingError(
                "unsupported_beam", "stateful decoding supports one greedy beam"
            )
        if type(do_sample) is not bool or do_sample:
            raise StatefulConstrainedDecodingError(
                "unsupported_sampling", "stateful decoding requires greedy sampling"
            )
        if type(num_return_sequences) is not int or num_return_sequences != 1:
            raise StatefulConstrainedDecodingError(
                "unsupported_beam", "stateful decoding supports one return sequence"
            )
        use_case_ids = tuple(approved_use_case_ids)
        if not 2 <= len(use_case_ids) <= 4:
            raise StatefulConstrainedDecodingError(
                "invalid_configuration", "exactly two to four use cases are required"
            )
        if any(
            not isinstance(item, str)
            or not item
            or item != item.strip()
            or len(item) > 128
            for item in use_case_ids
        ):
            raise StatefulConstrainedDecodingError(
                "invalid_configuration", "approved use-case IDs are invalid"
            )
        if len(use_case_ids) != len(set(use_case_ids)):
            raise StatefulConstrainedDecodingError(
                "invalid_configuration", "approved use-case IDs must be unique"
            )
        self.prompt_token_length = prompt_token_length
        self.approved_use_case_ids = use_case_ids
        self.generation_eos_token_id = generation_eos_token_id
        self.model_vocabulary_size = model_vocabulary_size
        self._vocabulary = _TokenizerVocabulary(
            tokenizer,
            self.limits,
            generation_eos_token_id,
            model_vocabulary_size,
        )
        self._machine = _SemanticCandidateMachine(use_case_ids, self.limits)
        self._prompt_token_ids: tuple[int, ...] | None = None
        self._raw_token_ids: tuple[int, ...] = ()
        self._generated_token_ids: tuple[int, ...] = ()
        self._last_allowed: tuple[int, ...] | None = None
        self._last_allowed_prefix: tuple[int, ...] | None = None
        self._callback_count = 0
        self._mask_compute_count = 0
        self._allowed_observations = 0
        self._masked_observations = 0
        self._rejection_counts: dict[str, int] = {}
        self._forced_token_positions: list[ForcedTokenPosition] = []
        self._failed_code = ""
        self._finalized = False
        self._completion: StatefulConstrainedGenerationCompletion | None = None
        self._started_at = time.monotonic()

    @property
    def generated_token_ids(self) -> tuple[int, ...]:
        return self._generated_token_ids

    @property
    def raw_token_ids(self) -> tuple[int, ...]:
        return self._raw_token_ids

    @property
    def is_complete(self) -> bool:
        return self._finalized

    def _fail(self, code: str, message: str) -> None:
        if not self._failed_code:
            self._failed_code = code
        raise StatefulConstrainedDecodingError(self._failed_code, message)

    def _check_elapsed(self) -> None:
        if time.monotonic() - self._started_at > self.limits.max_elapsed_seconds:
            self._fail(
                "resource_cap_exceeded", "generation elapsed time exceeds the hard cap"
            )

    @staticmethod
    def _ids(value: object) -> tuple[int, ...]:
        converter = getattr(value, "tolist", None)
        if callable(converter):
            value = converter()
        if not isinstance(value, (list, tuple)):
            raise StatefulConstrainedDecodingError(
                "unsupported_batch", "input_ids must be one-dimensional"
            )
        if value and isinstance(value[0], (list, tuple)):
            raise StatefulConstrainedDecodingError(
                "unsupported_batch", "input_ids must be one-dimensional"
            )
        result: list[int] = []
        for item in value:
            if type(item) is not int or item < 0:
                raise StatefulConstrainedDecodingError(
                    "invalid_configuration", "input_ids contain an invalid token ID"
                )
            result.append(item)
        return tuple(result)

    def _observe_prefix(self, input_ids: object) -> None:
        ids = self._ids(input_ids)
        if any(item >= self.model_vocabulary_size for item in ids):
            self._fail(
                "invalid_configuration",
                "input_ids contain a token outside the model vocabulary",
            )
        if self._prompt_token_ids is None:
            if len(ids) != self.prompt_token_length:
                self._fail(
                    "prefix_divergence",
                    "the first callback must receive the exact prompt length",
                )
            self._prompt_token_ids = ids
            self._last_allowed_prefix = ()
            return
        if len(ids) < self.prompt_token_length:
            self._fail("prefix_divergence", "the captured prompt prefix was truncated")
        if ids[: self.prompt_token_length] != self._prompt_token_ids:
            self._fail("prefix_divergence", "the captured prompt prefix changed")
        generated = ids[self.prompt_token_length :]
        if generated == self._raw_token_ids:
            return
        if (
            len(generated) != len(self._raw_token_ids) + 1
            or generated[:-1] != self._raw_token_ids
        ):
            self._fail(
                "prefix_divergence",
                "generation prefix is not one greedy continuation",
            )
        selected = generated[-1]
        if self._last_allowed is None or selected not in self._last_allowed:
            self._fail(
                "prefix_divergence",
                "generation selected a token outside the preceding mask",
            )
        if selected == self.generation_eos_token_id:
            self._fail(
                "controller_closed",
                "EOS must be consumed only by finalize after complete JSON",
            )
        if len(generated) > self.limits.max_generated_tokens:
            self._fail(
                "resource_cap_exceeded", "generated token count exceeds the hard cap"
            )
        piece = self._vocabulary.id_to_piece.get(selected)
        if piece is None:
            self._fail(
                "tokenizer_incompatible", "selected token has no stable decoded piece"
            )
        task = self._machine.current_task
        forced_reason = ""
        if task is not None:
            if task.kind == "literal":
                forced_reason = task.mask_code
            elif task.kind == "boundary" and len(task.options) == 1:
                forced_reason = task.mask_code
            elif task.kind == "choice":
                viable = [
                    option
                    for option in task.options
                    if option.startswith(task.value)
                ]
                if len(viable) == 1:
                    forced_reason = task.mask_code
            elif task.kind in {"text", "stable_id"} and piece == '"':
                forced_reason = "json_string_boundary"
        if forced_reason:
            self._forced_token_positions.append(
                ForcedTokenPosition(
                    generated_position=len(generated),
                    token_id=selected,
                    reason=forced_reason,
                )
            )
        try:
            self._machine.feed(piece)
        except _PrefixRejected as exc:
            self._fail(
                "parser_state_drift",
                f"selected token diverged from parser state: {exc.code}",
            )
        self._raw_token_ids = generated
        self._generated_token_ids = generated
        replay = "".join(
            self._vocabulary.id_to_piece[item] for item in self._raw_token_ids
        )
        decoded = self._vocabulary.decode_ids(self._raw_token_ids)
        if decoded != replay:
            self._fail(
                "parser_state_drift",
                "tokenizer sequence decoding is not compositional for selected tokens",
            )
        self._last_allowed_prefix = None

    def _allowed_for_task(self) -> tuple[int, ...]:
        if self._machine.complete:
            return (self.generation_eos_token_id,)
        task = self._machine.current_task
        assert task is not None
        if task.kind == "literal":
            return self._vocabulary.prefix_tokens(task.literal[task.position :])
        if task.kind in {"choice", "boundary"}:
            allowed: set[int] = set()
            for option in task.options:
                if not option.startswith(task.value):
                    continue
                suffix = option[len(task.value) :]
                allowed.update(self._vocabulary.prefix_tokens(suffix))
            return tuple(sorted(allowed))
        if task.kind in {"text", "stable_id"}:
            if not task.opened:
                return self._vocabulary.exact('"')
            if task.kind == "text":
                remaining = task.max_length - len(task.decoded_value)
                if task.escape_state == "escape":
                    escape_characters = tuple(_JSON_SIMPLE_ESCAPES) + ("u",)
                    if not task.decoded_value:
                        escape_characters = tuple(
                            item
                            for item in escape_characters
                            if item == "u"
                            or not _JSON_SIMPLE_ESCAPES.get(item, "").isspace()
                        )
                    allowed: set[int] = set()
                    for character in escape_characters:
                        allowed.update(self._vocabulary.exact(character))
                    return tuple(sorted(allowed))
                if task.escape_state == "unicode":
                    digits = _JSON_HEX_DIGITS
                    if (
                        len(task.unicode_digits) == 3
                        and not task.decoded_value
                    ):
                        digits = frozenset(
                            character
                            for character in digits
                            if not chr(
                                int(task.unicode_digits + character, 16)
                            ).isspace()
                        )
                    allowed = set()
                    for character in digits:
                        allowed.update(self._vocabulary.exact(character))
                    return tuple(sorted(allowed))
                values = self._vocabulary.text_tokens(
                    remaining, initial=not task.decoded_value
                )
                if remaining > 0:
                    values = (*values, *self._vocabulary.exact("\\"))
            else:
                remaining = task.max_length - len(task.value)
                values = self._vocabulary.stable_tokens(
                    remaining, initial=not task.value
                )
            if self._machine.can_close_string(task):
                return (*values, *self._vocabulary.exact('"'))
            return values
        self._fail("parser_state_drift", "unknown constrained parser task")
        raise AssertionError("unreachable")

    def prefix_allowed_tokens_fn(
        self, batch_id: int, input_ids: object
    ) -> list[int]:
        """Transformers-compatible greedy prefix mask."""

        if self._finalized:
            self._fail("controller_closed", "constrained generation is finalized")
        if self._failed_code:
            self._fail(self._failed_code, "constrained generation already failed")
        if type(batch_id) is not int or batch_id != 0:
            self._fail(
                "unsupported_batch", "stateful decoding supports only batch index zero"
            )
        self._check_elapsed()
        self._callback_count += 1
        self._observe_prefix(input_ids)
        if (
            self._last_allowed is not None
            and self._last_allowed_prefix == self._raw_token_ids
        ):
            return list(self._last_allowed)
        allowed = self._allowed_for_task()
        if not allowed:
            self._fail("no_legal_token", "no tokenizer token satisfies the next state")
        if any(
            type(token_id) is not int
            or token_id < 0
            or token_id >= self.model_vocabulary_size
            for token_id in allowed
        ):
            self._fail(
                "parser_state_drift",
                "constraint mask contains a token outside the model vocabulary",
            )
        self._mask_compute_count += 1
        self._allowed_observations += len(allowed)
        masked = self.model_vocabulary_size - len(set(allowed))
        self._masked_observations += masked
        task = self._machine.current_task
        mask_code = "complete_eos_only" if task is None else task.mask_code
        self._rejection_counts[mask_code] = (
            self._rejection_counts.get(mask_code, 0) + masked
        )
        self._last_allowed = allowed
        self._last_allowed_prefix = self._raw_token_ids
        return list(allowed)

    def replay_raw_bytes(self) -> bytes:
        """Return the exact token replay bytes without repair or normalization."""

        if not self._raw_token_ids:
            return b""
        decoded = self._vocabulary.decode_ids(self._raw_token_ids)
        replay = "".join(
            self._vocabulary.id_to_piece[item] for item in self._raw_token_ids
        )
        if decoded != replay:
            self._fail(
                "parser_state_drift", "raw token replay changed decoded text"
            )
        return decoded.encode("utf-8")

    def audit_summary(self) -> StatefulConstraintAuditSummary:
        raw = b""
        raw_unmodified = False
        if self._raw_token_ids and not self._failed_code:
            try:
                raw = self.replay_raw_bytes()
                raw_unmodified = self._finalized
            except StatefulConstrainedDecodingError:
                raw = b""
        status = (
            "failed"
            if self._failed_code
            else "complete"
            if self._finalized
            else "active"
        )
        return StatefulConstraintAuditSummary(
            schema_version=STATEFUL_CONSTRAINED_DECODING_AUDIT_SCHEMA_VERSION,
            treatment_id=STATEFUL_CONSTRAINED_GENERATION_TREATMENT_ID,
            treatment_version=STATEFUL_CONSTRAINED_GENERATION_TREATMENT_VERSION,
            status=status,
            execution_profile="local_smoke",
            success_interpretation="stateful_constrained_generation_only",
            unconstrained_first_pass_model_success_claimed=False,
            formal_quality_claimed=False,
            h1_or_gold_used=False,
            raw_repair_performed=False,
            approved_use_case_ids=self.approved_use_case_ids,
            model_owned_fields=_MODEL_OWNED_FIELDS,
            constraint_owned_fields=_CONSTRAINT_OWNED_FIELDS,
            forced_token_positions=tuple(self._forced_token_positions),
            symbol_table_transitions=tuple(self._machine.transitions),
            callback_count=self._callback_count,
            mask_compute_count=self._mask_compute_count,
            model_vocabulary_size=self.model_vocabulary_size,
            allowed_token_observations=self._allowed_observations,
            masked_token_observations=self._masked_observations,
            elapsed_milliseconds=max(
                0, int((time.monotonic() - self._started_at) * 1000)
            ),
            rejection_counts=tuple(sorted(self._rejection_counts.items())),
            generated_token_ids=self._generated_token_ids,
            raw_token_ids=self._raw_token_ids,
            generation_eos_token_id=self.generation_eos_token_id,
            complete=self._finalized,
            raw_unmodified=raw_unmodified,
            raw_byte_length=len(raw),
            raw_sha256=hashlib.sha256(raw).hexdigest() if raw else "",
            error_code=self._failed_code,
        )

    def finalize(
        self, output_ids: object
    ) -> StatefulConstrainedGenerationCompletion:
        """Finalize exactly one complete raw JSON followed by EOS."""

        if self._completion is not None:
            return self._completion
        if self._failed_code:
            self._fail(self._failed_code, "constrained generation already failed")
        self._check_elapsed()
        if self._prompt_token_ids is None:
            self._fail(
                "incomplete_generation", "prefix callback was never initialized"
            )
        ids = self._ids(output_ids)
        if any(item >= self.model_vocabulary_size for item in ids):
            self._fail(
                "invalid_configuration",
                "final output contains a token outside the model vocabulary",
            )
        if (
            len(ids) < self.prompt_token_length
            or ids[: self.prompt_token_length] != self._prompt_token_ids
        ):
            self._fail("prefix_divergence", "final output prompt binding changed")
        generated = ids[self.prompt_token_length :]
        expected = (*self._raw_token_ids, self.generation_eos_token_id)
        if generated != expected:
            self._fail(
                "incomplete_generation",
                "final output must be the observed complete JSON followed by EOS",
            )
        if not self._machine.complete:
            self._fail(
                "incomplete_generation", "semantic-candidate JSON is incomplete"
            )
        if self._last_allowed != (self.generation_eos_token_id,):
            self._fail(
                "incomplete_generation",
                "EOS was not independently exposed after complete JSON",
            )
        raw = self.replay_raw_bytes()
        try:
            candidate = parse_provider_raw_response(
                ProviderRawResponse.from_bytes(raw)
            )
        except (TypeError, ValueError) as exc:
            self._fail(
                "invalid_completion",
                "complete bytes failed the unchanged strict semantic-candidate parser",
            )
            raise AssertionError("unreachable") from exc
        if {
            item.use_case_id for item in candidate.use_case_mappings
        } != set(self.approved_use_case_ids):
            self._fail(
                "invalid_completion",
                "complete candidate does not bind the approved use cases",
            )
        if any(
            item.source_state_stable_id == item.target_state_stable_id
            for item in candidate.interactions
        ):
            self._fail(
                "invalid_completion", "complete candidate contains a self-loop"
            )
        self._generated_token_ids = generated
        self._finalized = True
        audit = self.audit_summary()
        completion = StatefulConstrainedGenerationCompletion(
            schema_version=STATEFUL_CONSTRAINED_DECODING_COMPLETION_SCHEMA_VERSION,
            treatment_id=STATEFUL_CONSTRAINED_GENERATION_TREATMENT_ID,
            treatment_version=STATEFUL_CONSTRAINED_GENERATION_TREATMENT_VERSION,
            raw_bytes=raw,
            raw_token_ids=self._raw_token_ids,
            generated_token_ids=generated,
            raw_sha256=hashlib.sha256(raw).hexdigest(),
            candidate_sha256=candidate.sha256(),
            complete=True,
            raw_unmodified=True,
            audit=audit,
        )
        self._completion = completion
        return completion


def create_stateful_constrained_generation(
    tokenizer: object,
    prompt_token_length: int,
    approved_use_case_ids: Sequence[str],
    *,
    generation_eos_token_id: int,
    model_vocabulary_size: int,
    limits: ConstraintLimits | None = None,
    batch_size: int = 1,
    num_beams: int = 1,
    do_sample: bool = False,
    num_return_sequences: int = 1,
) -> StatefulConstrainedGeneration:
    """Create the approved local-only v1 treatment controller."""

    return StatefulConstrainedGeneration(
        tokenizer,
        prompt_token_length,
        approved_use_case_ids,
        generation_eos_token_id=generation_eos_token_id,
        model_vocabulary_size=model_vocabulary_size,
        limits=limits,
        batch_size=batch_size,
        num_beams=num_beams,
        do_sample=do_sample,
        num_return_sequences=num_return_sequences,
    )
